event-flow:
  enabled: true
  scan-packages: com.github.vovten.eventflow.example
  publisher:
    enabled: true
    transactional: true
    retry:
      enabled: true
      max-attempts: 3
    silent: true
    channels:
      - name: internal
        transports:
          - name: kafka
            servers: localhost:9092
            topic: test
  dispatcher:
    enabled: true
    transports:
      - name: kafka
        topic: test
        servers: localhost:9092