event-flow:
  enabled: true
  publisher:
    enabled: true
    transactional: true
    silent: true
    retry:
      enabled: true
      max-attempts: 3
    async:
      enabled: true
    channels:
      - name: internal
        transports:
          - name: local-queue
      - name: external
        transports:
          - name: kafka
            servers: localhost:9092
            topic: test2
            serialization: myJson
      - name: broadcast
        transports:
          - name: kafka
            servers: localhost:9092
            topic: test2
  dispatcher:
    enabled: true
    listener-packages: io.github.vovten.eventflow.example
    deserialization:
      allowed-event-packages:
        - com.custom
    idempotent:
      enabled: true
    transports:
      - name: local-queue
      - name: kafka
        topic: test2
        servers: localhost:9092

