event-flow:
  enabled: false
  scan-packages: com.github.vovten.eventflow.example
  publisher:
    enabled: true
    transactional: true
    retry:
      enabled: true
      max-attempts: 3
      initial-delay: 100ms
      multiplier: 2.0
    silent: false
    channels:
      - name: internal
        transports:
          - name: in-memory
            capacity: 1000
